[package]
name = "game_engine"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.30.5"
egui = "0.29.0"
ash = "0.38.0"
ash-window = "0.13.0"
nalgebra-glm = "0.19.0"
log = "0.4.14"
env_logger = "0.11.5"
